apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorten-url-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: shorten
  template:
    metadata:
      labels:
        component: shorten
    spec:
      containers:
        - name: shorten-url
          image: shaibad/multi-shorten-url
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: env-config-map
          env:
            - name: HANDLER_PATH
              value: /shorten_url
            - name: HANDLER_METHOD
              value: POST
            - name: HANDLER_PORT
              value: '5000'
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD